import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import Services from "../components/Services";
import Team from "../components/Team";
import { HomePageType, ServiceHeader, ServicesType, TeamType } from "../types";

interface Props {
  data: HomePageType;
  dataServiceHeader: ServiceHeader;
  dataServices: ServicesType[];
  dataTeam: TeamType[];
}

const Home: NextPage<Props> = ({
  data,
  dataServiceHeader,
  dataServices,
  dataTeam,
}) => {
  return (
    <>
      <Head>
        <title>Arhitektur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        title={data.banner_content.title}
        content={data.banner_content.content}
      />
      <Services
        preTitle={dataServiceHeader.services_block.preTitle}
        title={dataServiceHeader.services_block.title}
        data={dataServices}
      />
      <Team
        title={dataServiceHeader.team_block.title}
        preTitle={dataServiceHeader.team_block.preTitle}
        data={dataTeam}
      />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("http://localhost:5001/homepage");
  const data: HomePageType = await res.json();

  const resServiceHeader = await fetch("http://localhost:5001/services_page");
  const dataServiceHeader: ServiceHeader = await resServiceHeader.json();

  const resServices = await fetch("http://localhost:5001/services");
  const dataServices: ServicesType[] = await resServices.json();

  const resTeam = await fetch("http://localhost:5001/team");
  const dataTeam: TeamType[] = await resTeam.json();

  return {
    props: {
      data,
      dataServiceHeader,
      dataServices,
      dataTeam,
    },
  };
};
