import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import { IBanner, IBlogs, IProduct } from "../interfaces/types";

interface Props {
  data: IBanner;
  featuredProducts: IProduct[];
  dataBlogs: IBlogs[];
}

const Home: NextPage<Props> = ({ data, featuredProducts, dataBlogs }) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner data={data} />

      <CategoryPicker />

      <FeaturedProducts featuredProducts={featuredProducts} />

      <FeaturedBlogs data={dataBlogs} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch("http://localhost:5001/banner_content");
  const data: IBanner = await res.json();

  const resFeaturedProduct = await fetch(
    "http://localhost:5001/products/?_limit=4"
  );
  const featuredProducts: IProduct[] = await resFeaturedProduct.json();

  const ressBlogs = await fetch("http://localhost:5001/blogs/?_limit=3");
  const dataBlogs: IBlogs[] = await ressBlogs.json();

  return {
    props: {
      data,
      featuredProducts,
      dataBlogs,
    },
  };
};
