import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import BlogItem from "../components/BlogItem";
import PageTitle from "../components/PageTitle";
import ProductItem from "../components/ProductItem";
import { IBlogs, IProduct } from "../interfaces/types";

interface Props {
  dataProducts: IProduct[];
  dataBlogs: IBlogs[];
}

const Search: NextPage<Props> = ({ dataBlogs, dataProducts }) => {
  return (
    <>
      <Head>
        <title>Store - Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Search" />

      <div className="bg0 m-t-23 p-b-140 mt-5">
        <div className="container">
          {/* blogs  */}
          <>
            <h2 className="mb-5">Blogs</h2>
            <div className="row isotope-grid">
              {/* blog skeleton - search result */}
              <div className="col-4">
                {dataBlogs.map((el) => (
                  <BlogItem key={el.id} {...el} />
                ))}
              </div>
              {/* !! */}
            </div>
          </>

          {/* products */}
          <>
            <h2 className="mb-5">Products</h2>
            <div className="row isotope-grid">
              {/* product skeleton */}
              {dataProducts.map((el) => (
                <ProductItem
                  key={el.id}
                  image={el.img}
                  title={el.title}
                  price={el.price}
                  id={el.id}
                />
              ))}
              {/* !! */}
            </div>
          </>
        </div>
      </div>
    </>
  );
};

export default Search;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const queryValue = query.q;

  const resProducts = await fetch(
    `http://localhost:5001/products?q=${queryValue}`
  );
  const dataProducts: IProduct[] = await resProducts.json();

  const resBlogs = await fetch(`http://localhost:5001/blogs?q=${queryValue}`);
 const dataBlogs: IBlogs[] = await resBlogs.json();

  return {
    props: {
      dataProducts,
      dataBlogs,
    },
  };
};
