import Head from "next/head";
import HeroSection from "../components/elements/HeroSection";
import { GetStaticProps } from "next";
import AboutBlock from "../components/elements/AboutBlock";
import FeaturedCourses from "../components/elements/FeaturedCourses";
import Testimonials from "../components/elements/Testimonials";

export interface DataProps {
  title: string;
  content: string;
  testimonials_title: string;
  testimonials_content: string;
}

export interface AboutPageProp {
  title: string;
  first_content_block: string;
  first_image: string;
  second_content_block: string;
  second_image: string;
  third_content_block: string;
}

export interface CoursesPage {
  id: string;
  title: string;
  is_full: boolean;
  start_time: string;
  excerpt: string;
  content: string;
  image: string;
  category: string;
  fee: string;
  duration: string;
}

export interface TestimonialsProp {
  id: string;
  first_name: string;
  last_name: string;
  message: string;
  avatar: string;
}

interface HomeInterface {
  data: DataProps;
  dataAbout: AboutPageProp;
  datacourse: CoursesPage[];
  dataTestimonial: TestimonialsProp[];
}

export default function Home({
  data,
  dataAbout,
  datacourse,
  dataTestimonial,
}: HomeInterface) {
  // console.log(dataTestimonial);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection title={data.title} content={data.content} />
      <AboutBlock
        title={dataAbout.title}
        first_content_block={dataAbout.second_content_block}
        first_image={dataAbout.first_image}
      />
      <FeaturedCourses data={datacourse} />
      <Testimonials firstData={data} data={dataTestimonial} />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const ress = await fetch("http://localhost:5001/homepage");
  const data: DataProps = await ress.json();

  const ressAbout = await fetch("http://localhost:5001/about_page");
  const dataAbout: AboutPageProp = await ressAbout.json();

  const ressCourse = await fetch(
    "http://localhost:5001/courses?start=1&_limit=3"
  );
  const datacourse: CoursesPage[] = await ressCourse.json();

  const ressTestimonials = await fetch("http://localhost:5001/testimonials");
  const dataTestimonial: TestimonialsProp[] = await ressTestimonials.json();

  return {
    props: {
      data,
      dataAbout,
      datacourse,
      dataTestimonial,
    },
  };
};
